name: Deploy TypeScript App

on:
  workflow_dispatch: # Позволяет запускать workflow вручную через интерфейс GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js 22.11.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 5: Деплой на сервер
      - name: Deploy to server
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_KEY }}
          TARGET_DIR: ${{ secrets.DEPLOY_TARGET_DIR }}
        run: |
          echo "${KEY}" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -i private_key" . ${USER}@${HOST}:${TARGET_DIR}
        shell: bash

      # Шаг 6: Запуск приложения на сервере
      - name: Start application on server
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_KEY }}
          TARGET_DIR: ${{ secrets.DEPLOY_TARGET_DIR }}
        run: |
          echo "${KEY}" > private_key
          chmod 600 private_key
          ssh -i private_key ${USER}@${HOST} "
            cd ${TARGET_DIR} &&
            npm install --production &&
            NODE_ENV=production tsx -r dotenv/config src/index.ts dotenv_config_path=.env.prod
          "
        shell: bash
